[2024-05-31T04:59:34.973+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-31T04:59:34.999+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_weather_workflow_DAG_v04.load_csv_to_postgres manual__2024-05-31T04:06:10.739308+00:00 [queued]>
[2024-05-31T04:59:35.009+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_weather_workflow_DAG_v04.load_csv_to_postgres manual__2024-05-31T04:06:10.739308+00:00 [queued]>
[2024-05-31T04:59:35.010+0000] {taskinstance.py:2306} INFO - Starting attempt 6 of 11
[2024-05-31T04:59:35.022+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_csv_to_postgres> on 2024-05-31 04:06:10.739308+00:00
[2024-05-31T04:59:35.030+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2802) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-31T04:59:35.031+0000] {standard_task_runner.py:63} INFO - Started process 2804 to run task
[2024-05-31T04:59:35.030+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'my_weather_workflow_DAG_v04', 'load_csv_to_postgres', 'manual__2024-05-31T04:06:10.739308+00:00', '--job-id', '223', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpsya8u10t']
[2024-05-31T04:59:35.032+0000] {standard_task_runner.py:91} INFO - Job 223: Subtask load_csv_to_postgres
[2024-05-31T04:59:35.094+0000] {task_command.py:426} INFO - Running <TaskInstance: my_weather_workflow_DAG_v04.load_csv_to_postgres manual__2024-05-31T04:06:10.739308+00:00 [running]> on host cd9caf1c47f0
[2024-05-31T04:59:35.187+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Khang' AIRFLOW_CTX_DAG_ID='my_weather_workflow_DAG_v04' AIRFLOW_CTX_TASK_ID='load_csv_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-05-31T04:06:10.739308+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-31T04:06:10.739308+00:00'
[2024-05-31T04:59:35.189+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-31T04:59:35.225+0000] {base.py:84} INFO - Using connection ID 'postgres_connection_id' for task execution.
[2024-05-31T04:59:35.240+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-31T04:59:35.240+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-31T04:59:35.255+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=my_weather_workflow_DAG_v04, task_id=load_csv_to_postgres, run_id=manual__2024-05-31T04:06:10.739308+00:00, execution_date=20240531T040610, start_date=20240531T045935, end_date=20240531T045935
[2024-05-31T04:59:35.286+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-31T04:59:35.313+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-31T04:59:35.316+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
